### ISSUE TITLE
why is display of the surface so slow?

### ISSUE THREAD

**Issue by LollipopFt** [sotrh/learn-wgpu#377] opened 2022-07-04 11:43 UTC
i am currently on the 2nd tutorial where i make the surface. I realised that the time between the white window appearing and the blue surface being applied is about 1 second even on `--release`. is this intended?

**Comment by HeavyRain266** [comment] 2022-07-04 12:20
Looks like it's general behaviour caused by Winit/WGPU because even bevy or any other library seems to have even longer loading time... there is tiny hack where you set window visibility to false ny default and then make it visible on MainEventsCleared (or similiar) event from winit. You can now see window with blue surface by default.

**Comment by HeavyRain266** [comment] 2022-07-04 15:48
> however, running the [vulkano-rs](https://github.com/vulkano-rs/vulkano) triangle example shows that it runs much faster - it's about 5x as fast.

Vulkano is safe vulkan abstraction while wgpu implements still evolving and incomplete graphics API on top of vulkan, directx, metal, gles and webgl, there always will be worse performance than pure bindings to given API, I expect that ash is even faster than vulkano because it doesn't contains layers of safe abstractions like both wgpu and vulkano.

**Comment by sotrh** [comment] 2023-03-25 23:29
Seems like discussion has stopped here, so I'm going to close this for now.

**Closed by sotrh** 2023-03-25 23:29 UTC
