### ISSUE TITLE
error matching VERTEX shader requirements against the pipeline

### ISSUE THREAD

**Issue by Sable-20** [sotrh/learn-wgpu#253] opened 2021-10-22 18:05 UTC
while it is entirely possible im pulling a dum dum again I dont think tahts it in this specific case.

I am building my application and getting the error message 
```
[2021-10-22T18:03:42Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `Render Pipeline`
    error matching VERTEX shader requirements against the pipeline
    location[9] Float32x3 interpolated as Some(Perspective) with sampling Some(Center) is not provided by the previous stage outputs
    input is not provided by the earlier stage in the pipeline

```

which is not the most specific error message. it gives me some but not all so I am a little bit lost on what to do from here. Ill continue to attempt to debug on my own

**Comment by yasushisakai** [comment] 2021-12-10 23:21
just came across the same issue but noticed that I wasn't putting the right `shader_location` in the `VertexAtrribute` field

**Comment by sotrh** [comment] 2022-04-14 22:23
It's been a few months, and without some way to reproduce I really can't help much. On top of that, wgpu has been updated since this was posted, so if it's an internal error it may not be an issue anymore. Because of this I'm opting to close this issue.

**Closed by sotrh** 2022-04-14 22:23 UTC

**Comment by arbaregni** [comment] 2024-03-26 01:13
Hi, just ran into this. I've attached log files 
I've been mostly following the example [here](https://github.com/bevyengine/bevy/blob/main/examples/shader/shader_material_glsl.rs).

[error.log](https://github.com/sotrh/learn-wgpu/files/14751065/error.log)
