### ISSUE TITLE
Vulkan validation issues

### ISSUE THREAD

**Issue by Grindv1k** [sotrh/learn-wgpu#165] opened 2021-04-17 21:34 UTC
```
[2021-04-17T21:23:10Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-04627 (1158829633)] : Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-04627 ] Object 0: handle = 0xb5f68b000000000e, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x45125641 | vkCmdBeginRenderPass(): Image view #0 created from an image with usage set as 0x11, but image info #0 used to create the framebuffer had usage set as 0x10 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView with an inherited usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/1.2-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-04627)
    object info: (type: RENDER_PASS, hndl: 13111820197252038670)
```

Getting a lot of these running tutorial 2 (not tutorial 1).

```
cd code/beginner/tutorial2-swapchain
cargo run --bin tutorial2-swapchain
```

I saw another closed issue with another error message, where you requested a trace.
I captured one, allowing the example to run ~5 seconds, attached: [trace.zip](https://github.com/sotrh/learn-wgpu/files/6330080/trace.zip).

Also, vulkan configuration says I have (might help?):

Vulkan Development Status:
- Layers override: "Validation" configuration
- $VULKAN_SDK SDK path: C:\VulkanSDK\1.2.170.0
- Vulkan Loader version: 1.2.170
- User-Defined Layers Paths from $VK_LAYER_PATH: None
- User-Defined Layers Paths from Vulkan Configurator: None
- Available Layers:
    - VK_LAYER_NV_optimus (1.2.168)
    - VK_LAYER_OBS_HOOK (1.2.131)
    - VK_LAYER_VALVE_steam_overlay (1.2.136)
    - VK_LAYER_VALVE_steam_fossilize (1.2.136)
    - VK_LAYER_EOS_Overlay (1.2.136)
    - VK_LAYER_EOS_Overlay (1.2.136)
    - VK_LAYER_LUNARG_override (1.2.170)
    - VK_LAYER_LUNARG_api_dump (1.2.170)
    - VK_LAYER_LUNARG_device_simulation (1.2.170)
    - VK_LAYER_LUNARG_gfxreconstruct (1.2.170)
    - VK_LAYER_KHRONOS_synchronization2 (1.2.170 - BETA)
    - VK_LAYER_KHRONOS_validation (1.2.170)
    - VK_LAYER_LUNARG_monitor (1.2.170)
    - VK_LAYER_LUNARG_screenshot (1.2.170)
- Physical Devices:
    - NVIDIA GeForce RTX 2080 Ti (Discrete GPU) with Vulkan 1.2.168

**Comment by sotrh** [comment] 2021-04-19 02:53
I'll take a look into this.

**Comment by ifsheldon** [comment] 2021-05-16 18:29
Does this issue have any corelation to what I encountered? 
I just finished the pipeline chapter. Although the program runs fine, there is an error from wgpu.
`[2021-05-16T18:21:00Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }`
I cannot find it anywhere on the web.
I am using wgpu-rs 0.8 now and I have modified the code based on 0.7 a bit to adjust to some API changes. If you want to see my code, feel free to see it [here](https://github.com/ifsheldon/Wenderer/tree/wgpu0.8). My project is intended for transferring my scientific visualization code based on OpenGL to web-gpu, but now I am just walking through the tutorial, so the code is basically the same as in the tutorial.

**Comment by sotrh** [comment] 2021-05-18 03:18
The validation error you're experiencing is likely due to me forgetting to remove a debug `in` variable from a shader.

**Comment by ifsheldon** [comment] 2021-05-18 18:54
I don't have your debug `in` variable in my shaders, so the shaders seem perfectly right to me, but I'm not sure whether `layout(location=0)` is the cause. I think the reason for `layout(location=0)` that you mentioned in your tutorial seems reasonable to me..... so I could not and can not see what goes wrong.....

**Comment by ifsheldon** [comment] 2021-05-24 17:45
I finally found where my error comes from. See this [issue](https://github.com/gfx-rs/wgpu-rs/issues/915). Maybe you should write a side note in this tutorial.

**Comment by sotrh** [comment] 2021-05-24 18:42
I've been switching the tutorial to use WGSL, which doesn't have this validation error so I'm going to close this issue for now. I may add a section for using GLSL and maybe even HLSL and Metal with wgpu, but that's not going to be a thing for a while.

**Closed by sotrh** 2021-05-24 18:42 UTC
